minor fix

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -159,14 +159,16 @@ jobs:
         working-directory: artifacts
         run: |
           codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
-          echo codeCoverage=${codeCoverage%?}
+          codeCoverage=${codeCoverage%?}
           echo "CODE_COVERAGE=$codeCoverage" >> $GITHUB_ENV
 
-      - name: Check if code-coverage is greater than threshold
-        run: |
-          codeCoverage=${{ env.CODE_COVERAGE }}
-          echo "currently code coverage is $codeCoverage%"
-
+  #      - name: Check if code-coverage is greater than threshold
+  #        run: |
+  #          codeCoverage=${{ env.CODE_COVERAGE }}
+  #          if (( $(echo "$codeCoverage < 92" | bc -l) )); then
+  #            echo "code coverage cannot be less than 92%, currently its $codeCoverage%"
+  #            exit 1
+  #          fi
   Submodule-Unit-Testing:
     name: Submodule Unit Testing (v${{ matrix.go-version }})🛠
     runs-on: ubuntu-latest
@@ -230,7 +232,7 @@ jobs:
     name: Upload Coverage📊
     runs-on: ubuntu-latest
     needs: [Example-Unit-Testing,PKG-Unit-Testing]
-    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/development') || (github.event_name == 'pull_request' && github.base_ref == 'development') }}
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development'}}
     steps:
       - name: Check out code into the Go module directory
         uses: actions/checkout@v4
@@ -245,14 +247,14 @@ jobs:
         run: |
           awk '!/^mode: / && FNR==1{print "mode: set"} {print}' ./Example-Test-Report/profile.cov > merged_profile.cov
           tail -n +2 ./PKG-Coverage-Report/profile.cov >> merged_profile.cov
-
-      - name: Display Merged Coverage
-        working-directory: artifacts
-        run: |
+          
+          # Echo the merged coverage percentage
           echo "Merged coverage summary:"
           go tool cover -func=merged_profile.cov
-          codeCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
-          echo "Merged Coverage Percentage: ${codeCoverage%?}%"
+
+          # Extract and display the total merged coverage percentage
+          mergedCoverage=$(go tool cover -func=merged_profile.cov | grep total | awk '{print $3}')
+          echo "Merged Coverage Percentage: ${mergedCoverage%?}%"
 
       - name: Upload
         uses: paambaati/codeclimate-action@v9.0.0
@@ -277,7 +279,7 @@ jobs:
 
       - name: Get dependencies
         run: |
-         go mod tidy
+          go mod tidy
 
       - name: Lint Root Module
         uses: golangci/golangci-lint-action@v6
